### ISSUE TITLE
Error in doc_parse_raw: Opening and ending tag mismatch: expr line 28 and equal_assign [76]

### ISSUE THREAD

**Issue by step-** [jimhester/lintr#403]
In RStudio 1.2.1335 Linux, R 3.6.1:
```
> lintr::lint("R/lintr-bug.R")
Error in doc_parse_raw(x, encoding = encoding, base_url = base_url, as_html = as_html,  : 
  Opening and ending tag mismatch: expr line 28 and equal_assign [76]
```
lintr-bug.R attached. 
I had just built lintr from github with packrat. I'm attaching packrat.lock so you can see all package versions involved.
[attachments.zip](https://github.com/jimhester/lintr/files/3567094/attachments.zip)

**Comment by russHyde** [comment]
Could you install `xmlparsedata` from github, eg, using `devtools::install_github("r-lib/xmlparsedata")`, please. On R.3.6 we were getting this `doc_parse_raw` error when parsing R code that contained equals-assignments; see here: https://github.com/r-lib/xmlparsedata/issues/5

**Comment by step-** [comment]
Indeed `xmlparsedata` from github fixed this issue. Now lintr prints three markers "Use <- not = for assignment" and terminates correctly. Thank you.

**Comment by csgillespie** [comment]
I'm now getting this error with R-devel on travis, but __not R-current (3.6). Any suggestions?

**Comment by russHyde** [comment]
Do you have a travis log we could look at or is it a private repo?

**Comment by csgillespie** [comment]
https://travis-ci.org/csgillespie/poweRlaw

**Comment by russHyde** [comment]
@csgillespie had a look at your inteRgrate travis log. OTOH I'm not sure what the problem is.

Can I ask why you use `devtools::install(..., upgrade = "never")`.  Can you be sure you're using lintr>=2 and xmlparsedata >=1.0.3 in your travis run?.

FWIW: our logs looked like this when we had issues with `doc_parse_raw` https://travis-ci.org/jimhester/lintr/builds/561186819?utm_source=github_status&utm_medium=notification

**Comment by russHyde** [comment]
Sorry, idsregard that. I can see the lintr 2 install in your poweRlaw log

**Comment by russHyde** [comment]
As a minor point, you're installing two differrent versions of lintr when running CI on poweRlaw. The 2.0.0 version when travis works on the `r_packages` stub of your .travis.yml; then the dev version when you install `integRate`. So, the dev version should be responsible for the failing call.

**Comment by russHyde** [comment]
I can't see any changes in R 3.7 changelog that would affect `get_parse_data` at present, and I'm not sure how I could debug against R3.7 locally. Would you mind if I do some experimental PRs against powerLaw?

**Comment by csgillespie** [comment]
Feel free to play around on the branch - it's just a test branch. I've removed all R files except 1 (https://github.com/csgillespie/poweRlaw/tree/lintr/R) to simplify things

**Comment by russHyde** [comment]
I ran lint_package() on your lintr branch in (todays release) of R-4.0.0 on windows with lintr 2.0.0, and xmlparsedata=1.0.3, xml2=1.2.2

Debugged both `xml2::read_xml` and `xmlparsedata::xml_parse_data`. The string passed to read_xml by xml_parse_data had an invalid header.

```
debug(xmlparsedata::xml_parse_data)
lint_package()
```
xml_parse_data returned a string with header containing `... encoding=\"UTF-8\"standalone=\"yes\" ...`


Note this change to xmlparsedata: https://github.com/r-lib/xmlparsedata/pull/7

The xml header construction should be fixed with current github version of xmlparsedata; suggest you add a install_github for xmlparsedata in your travis.yml

**Comment by csgillespie** [comment]
So I tried that:
 * https://travis-ci.org/csgillespie/poweRlaw/jobs/648443039
 * https://github.com/csgillespie/poweRlaw/blob/lintr/.travis.yml

Still no luck

**Comment by russHyde** [comment]
Apologies. That doesn't appear to fix it locally either (and doesn't really explain the R3.6 -> R-devel differences).

There's something wrong with how xmlparsedata handles the "expr_or_assign_or_help" tags returned by getParseData. This seems to be an xmlparsedata problem. But we'd need to make a smaller example before sending it to Gabor et al

**Comment by russHyde** [comment]
```
debug(xml2::read_xml)
cat("a = 123\n", file = "bbb.R")
lint("bbb.R")
... x is the parsed data ...
cat(x, file = "")
```

```
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<exprlist>
<expr_or_assign_or_help line1="1" col1="1" line2="1" col2="7" start="9" end="15">
<expr line1="1" col1="1" line2="1" col2="7" start="9" end="15">
<expr line1="1" col1="1" line2="1" col2="1" start="9" end="9">
<SYMBOL line1="1" col1="1" line2="1" col2="1" start="9" end="9">a</SYMBOL>
</expr>
<EQ_ASSIGN line1="1" col1="3" line2="1" col2="3" start="11" end="11">=</EQ_ASSIGN>
<expr line1="1" col1="5" line2="1" col2="7" start="13" end="15">
<NUM_CONST line1="1" col1="5" line2="1" col2="7" start="13" end="15">123</NUM_CONST>
</expr>
</expr_or_assign_or_help>
</expr>
</exprlist>
```
 All the `expr` tags start _after_ the `expr_or_assign_or_help` tag; but one of them is closed after the `expr_or_assign_or_help` tag is closed

**Comment by russHyde** [comment]
But, when you extract xml from the parsed code without going through lintr, it seems to parse OK.

```
cat(
  xmlparsedata::xml_parse_data(getParseData(parse("bbb.R"))), 
  file = ""
)
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<exprlist>
<expr_or_assign_or_help line1="1" col1="1" line2="1" col2="7" start="9" end="15">
<expr line1="1" col1="1" line2="1" col2="1" start="9" end="9">
<SYMBOL line1="1" col1="1" line2="1" col2="1" start="9" end="9">a</SYMBOL>
</expr>
<EQ_ASSIGN line1="1" col1="3" line2="1" col2="3" start="11" end="11">=</EQ_ASSIGN>
<expr line1="1" col1="5" line2="1" col2="7" start="13" end="15">
<NUM_CONST line1="1" col1="5" line2="1" col2="7" start="13" end="15">123</NUM_CONST>
</expr>
</expr_or_assign_or_help>
</exprlist>
```

**Comment by russHyde** [comment]
Reopened this issue, although it seems slightly different from the original issue.

**Comment by jimhester** [comment]
This should be fixed by #455 as well
